### PR TITLE
Add completor.vim integration

### PR DESCRIPTION
**Pull request by leocamelo**
Add [completor.vim](https://github.com/maralla/completor.vim) plugin integration.

[asciicast](https://asciinema.org/a/188273)

### CODE REVIEW

**Review by slashmili — CHANGES_REQUESTED** [review]
I would recommend to import `ElixirSenseClient` module directly to `pythonx/completor_elixir/__init__.py`. You may look at [deoplete](https://github.com/slashmili/alchemist.vim/blob/master/rplugin/python3/deoplete/sources/alchemist.py) plugin as an example.

The current  way of executing `elixir_sense_wrapper.py` on every autocomplete request is slow and not efficient.

BTW you can show more information like the function signature. 
screen shot 2018-06-22 at 11 40 45

**Comment by leocamelo** [comment]
Thanks for the feedback, I will send soon another commit with the fixes. :)

**Comment by leocamelo** [comment]
Wrapper for elixir_sense removed, completor.vim integrated using ElixirSenseClient.
Thanks again by the tip, now run faster. :D

**Comment by slashmili** [comment]
@leocamelo thank you 🎉

**Comment by leocamelo** [comment]
Thanks, @slashmili ! I will send a PR to the wiki with this new :)

**Pull request merged**
