### PR TITLE
Disable syslog

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by slashmili** [comment]
@wsdjeg the syslog is not enabled unless _debug_ is set to true here:

https://github.com/slashmili/alchemist.vim/blob/master/elixir_sense_client#L6

Is there any reason that you removed the import?

**Comment by wsdjeg** [comment]
syslog only works in linux, it does not support windows.

**Review by slashmili — CHANGES_REQUESTED** [review]
We can wrap the import in try catch

We do need the syslog module when people want to report issue.

**Comment by wsdjeg** [comment]
Sorry, I do not family with py, so I can not finished, :(

**Comment by slashmili** [comment]
Fixed in #148

**Comment by wsdjeg** [comment]
@slashmili Thanks

**Pull request closed without merging**
