### PR TITLE
Make server self destruct

### PR DESCRIPTION
**Pull request by carloslima**

### CODE REVIEW

**Comment by carloslima** [comment]
This depends on (and includes) #67

**Comment by slashmili** [comment]
LOL, I never thought of this 👍

**Comment by lATAl** [comment]
@slashmili This make error with elixir 1.2.3

**Comment by slashmili** [comment]
@lATAl can you provide the errors?

**Comment by lATAl** [comment]
When I run ```elixir
~/.dotfiles/vim/vendor/alchemist.vim/alchemist-server/run.exs --env=dev
--listen``` for debug. Output an error
```
(EXIT from #PID<0.47.0>) shutdown: failed to start child: SelfDestructTimer
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error,
{:undef, [{DateTime, :utc_now, [], []}, {SelfDestructTimer, :now, 0, [file:
'/Users/tuan/.dotfiles/vim/vendor/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex',
line: 24]}, {Agent.Server, :init, 1, [file: 'lib/agent/server.ex', line:
8]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]},
{:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}

/Users/tuan/.dotfiles/vim/vendor/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:4:
SelfDestructTimer.start_link/0

```

I think the reason is that DateTime is only available from version 1.3

**Comment by slashmili** [comment]
@lATAl Ah! that's correct :(

Well we can check if elixir is older and don't enable this feature, what do you think?

**Comment by lATAl** [comment]
@slashmili Yes. Can you do that?

**Comment by slashmili** [comment]
@lATAl can you check `support-elixir1.2` branch?

**Pull request merged**
