### PR TITLE
Fix missing conversion of filter object.

### PR DESCRIPTION
**Pull request by gmcabrita**

### CODE REVIEW

**Comment by slashmili** [comment]
Oops! I missed that.

Thanks :+1:

**Comment by gmcabrita** [comment]
No problem. I was actually starting work on a patch for python3 support but you beat me to it :)

**Comment by slashmili** [comment]
Sorry! If you mentioned it, I would happily leave it to you.

Are you familiar `YouCompleteMe`? I have hard time figuring out why it's not working with `YouCompleteMe`

**Comment by gmcabrita** [comment]
It's fine :)

And no I haven't used YouCompleteMe.

**Pull request merged**
