### PR TITLE
WIP: Xref callers

### LINKED ISSUE #51: implement xref
The idea is to use xref to find the places that a given module/function is used and helps users to refactor a code!

alchemist-server doesn't support xref yet, need to implement the base there first.

it should work like this:

```
:ExRef MyApp.Repo -> open a window that list of files that uses this module
:ExRef MyApp.User.changeset -> open a window that list of files that uses this function
```

### PR DESCRIPTION
**Pull request by carloslima**
Closes #51

### CODE REVIEW

**Comment by carloslima** [comment]
@slashmili What do you like better? 

Something along the lines of
https://github.com/slashmili/alchemist.vim/pull/68/commits/94a02da487f6cd70ddc63acf1bcae22710cfa9d7

or the simpler approach of
https://github.com/slashmili/alchemist.vim/pull/68/commits/967ab84896feee349bce6bb2fd511dd46af9c119
?

I'm leaning towards just calling `mix`. Would you agree?

**Comment by carloslima** [comment]
Comparing the commits is somewhat unfair.

The first one is a stripped down copy of the mix task implementation, missing the vim integration.

The second one is the vim integration without the elixir part since it calls `mix xref ...` directly from the python client instead of relying on the alchemist-server for this.

**Comment by slashmili** [comment]
I got an error but I can't see the full python stack trace. I'll check it later.

BTW does it work in umbrella projects?

**Comment by briandunn** [comment]
Anything I can do to help get this merged? Would love to be able to pull up a caller list in the cw.

**Comment by slashmili** [comment]
@briandunn actually we had some discussion over chat which is not included here.

There are two problems:
1. It won't work if you have used the function in your test environment(`.exs` files are not compiled)
2. It doesn't work well in umbrella projects.

when you run the `mix xref callers XXXXXXXX` on an umbrella project.
it returns something like:

```
lib/app_a/my_a_mod.ex:11 XXXXXXXX
web/controllers/api/my_api.ex:24 XXXXXXXX
lib/app_b/my_b_mod.ex:9 XXXXXXXX
```

The sub app name is missing on that path to file.


Any suggestion would be appreciated

**Comment by jfornoff** [comment]
Hey,

I got a PR into Elixir yesterday, that gives info on the sub app name.
Not a full path, but the `mix xref` output is prefixed with the sub app name, see [here](https://github.com/elixir-lang/elixir/issues/6963). Maybe that helps with making this work :-)

**Pull request closed without merging**
