### PR TITLE
Improve module name lookup when nested modules present

### PR DESCRIPTION
**Pull request by gasparch**
- detect matchit and vim-elixir plugins presence
     - use them to skip over nested modules when looking up for module name

Alchemist.vim was failing to lookup function names in module like

```elixir

defmodule A do
    defmodule B do
        def foo() do
           :ok
        end
    end

    def bar() do
        :ok
    end
end
```

`exdef` on function bar was thinking that it is in module **B**, while in reality it is in **A**. 
Implementing own do/end matcher is quite a feat and matchit already does it reasonably well (and also needs correct syntax highlight from vim-elixir), so let's rely on it to fix lookup in some cases.

### CODE REVIEW

**Comment by gasparch** [comment]
@slashmili also ping on this plz :)))) at least give it a try :)

**Comment by slashmili** [comment]
@gasparch I'll use this branch for few days and will merge it later, would it work for you?

**Comment by gasparch** [comment]
Sure, I use a fork anyway, but I hope this may be useful for others. As I use a lot of submodules for defining structures inside the module - inabilicty of alchemist to find and jump to function is just annoying :))))

**Comment by slashmili** [comment]
Thanks for your contribution 🎉

**Comment by gasparch** [comment]
Welcome :)

**Comment by gasparch** [comment]
BTW you are welcome to check out this project and see how it works for you :) https://github.com/gasparch/vim-ide-elixir

I'm slowly creating better integrated set of plugins for elixir :) + some extra functionality not yet present in other plugins (trace/folds/etc)

**Comment by slashmili** [comment]
nice! sure I'll try it out

**Pull request merged**
